export enum Actions {
  FETCH_TODOS = 'FETCH_TODOS',
  ADD_TODO = 'ADD_TODO',
  UPDATE_TODO = 'UPDATE_TODO',
  DELETE_TODO = 'DELETE_TODO',
  SET_SHOW_ALL_FILTER = 'SET_SHOW_ALL_FILTER',
  SET_SHOW_COMPLETE_FILTER = 'SET_SHOW_COMPLETE_FILTER',
  SET_SHOW_INCOMPLETE_FILTER = 'SET_SHOW_INCOMPLETE_FILTER',
}
